5주차 리뷰 부탁드립니다.
kakao-tech-campus-2nd-step3/Team1_BE pull request #38
Opened 2024-10-04 13:07 UTC by Kdonghs

2024-10-05 00:59 UTC, yoo-jaein requested changes
5주차 고생 많으셨습니다.
코멘트 확인 부탁드려요!

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/DTO/InviteRequestDTO.java
> +    private Integer projectId;
projectId가 nullable한 값일까요?
Integer는 객체이므로 null 값을 가질 수 있습니다.

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/DTO/MemberDetailResponseDTO.java
> +    private ProjectEntity projectEntity;
엔티티를 그대로 dto에 포함시키는 것은 일반적으로 지양해야하는 방법입니다.
엔티티를 dto에 직접 포함시키면
1. 클라이언트에게 불필요한 정보(때로는 민감한 정보)까지 노출될 수 있습니다. 
2. 클라이언트의 요구사항에 맞춰 dto를 수정해야할 때가 많은데 그럴 경우 엔티티를 직접 수정하게 됩니다.

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/DTO/MemberRequestDTO.java
> +        @Size(max = 15, message = "이름은 공백 포함 최대 15글자까지 가능합니다.")
👍

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/DTO/TaskDTO.java
> +    public static class Update {
ProjectDTO에서 업데이트 관련 dto 이름이 ProjectUpdate인데, TaskDTO에서는 Update네요. 컨벤션을 한 쪽으로 맞추면 좋겠습니다!

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/controller/AuthController.java
> +    @GetMapping("/memberCode")
AttendUrlController 에는 /api/project/{project_id}/invite-link 처럼 케밥 케이스로 이름을 지었는데 다른 곳은 카멜케이스네요. api 엔드포인트 컨벤션도 하나로 통일하면 좋겠습니다!

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/controller/ProjectInviteController.java
> +
일반적으로 클래스 주석은 여기 작성합니다!

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/controller/TaskController.java
> +     */
👍

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/init/InitData.java
> +@Profile("dev")
👍

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/java/team1/BE/seamless/mapper/TaskMapper.java
> +public class TaskMapper {
매퍼에 대한 테스트도 있으면 좋겠습니다

2024-10-05 00:59 UTC, yoo-jaein commented on src/main/resources/application.properties
> +spring.mail.password=123
작업하시면서 계정 정보 노출되지 않도록 잘 관리하셔야겠네요..!

2024-10-05 01:03 UTC, yoo-jaein commented
> Soft Delete에 관해 
isDeleted의 필드를 true로 바꾸고 나면 그 데이터는 삭제된 것으로 간주합니다.
대신 해당 데이터를 findById 등으로 조회했을 때 데이터가 존재하니 예외가 발생하지 않겠죠? 
이렇게 다른 곳에서 관련 로직을 수정할 필요가 있습니다.

2024-10-05 01:07 UTC, yoo-jaein commented
> 연결되어 있는 객체의 정보를 가져오는 방법

네 맞습니다. ```@OneToMany```, ```@ManyToOne``` 등의 어노테이션은 엔티티 간의 관계를 정의하지만, 실제 객체 간의 연결을 자동으로 만들어주지는 않습니다. 
그래서 이게 우리가 객체 간의 실제 연결을 위해 연관관계 편의 메서드를 만들어서 쓰는 이유입니다.

검색하신 내용들도 맞습니다. 일반적으로 실무에서는 fetch join을 자주 사용하는 편이라 그대로 진행하시면 좋을 것 같습니다.

2024-10-07 09:47 UTC, yoo-jaein approved these changes
다음 단계 진행을 위해 머지하겠습니다.
화이팅!!

2024-10-07 09:47 UTC, merged

2024-10-07 13:07 UTC, seoyoung-dev commented on src/main/java/team1/BE/seamless/DTO/TaskDTO.java
> +    public static class Update {
넵 수정하겠습니다!